coderush/Models/InvoiceMaster.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace coderush.Models
{
     public class InvoiceMaster
    {
        public int Id { get; set; }
        [Required]
        [Display(Name = "ProjectId:")]

        public int ProjectId { get; set; }
        [Display(Name = "Amount:")]

        [Required]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Amount must be numeric")]
        public string Amount { get; set; }
        [Display(Name = "Duedate:")]

        [Required]
        public DateTime? Duedate { get; set; }
        [Display(Name = "InvoiceNumber:")]

        [Required]
        public string InvoiceNumber { get; set; }
        [Display(Name = "PendingAmount:")]

        public string PendingAmount { get; set; }
        public bool Isdeleted { get; set; }
        [Display(Name = "Isverify:")]
        public bool Isverify { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
    }
    public class InvoiceMasterDeatils
    {
        public List<InvoiceMasterViewModel> InvoiceMasterList { get; set; }
    }
    public class InvoiceMasterViewModel
    {
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public string Amount { get; set; }
        public DateTime? Duedate { get; set; }
        public string InvoiceNumber { get; set; }
        public string PendingAmount { get; set; }
        public int TotalAmount { get; set; }

    }
}

coderush/Controllers/InvoiceMasterController.cs
using coderush.Data;
using coderush.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using coderush.DataEnum;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using coderush.Models.ViewModels;

namespace coderush.Controllers
{
    [Authorize(Roles = "SuperAdmin")]
    public class InvoiceMasterController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly ApplicationDbContext _context;
        //private readonly IHostEnvironment _hostingEnvironment;
        public InvoiceMasterController(ILogger<HomeController> logger, UserManager<ApplicationUser> userManager,
           RoleManager<IdentityRole> roleManager,
           ApplicationDbContext context)
        //IHostEnvironment hostingEnvironment)
        {
            _logger = logger;
            _roleManager = roleManager;
            _userManager = userManager;
            _context = context;
            //_hostingEnvironment = hostingEnvironment;
        }
        public IActionResult InvoiceIndex()
        {
            //ViewBag.InvoiceSelectionList = Enum.GetValues(typeof(Expenses)).Cast<Expenses>().Select(v => new SelectListItem
            //{
            //    Text = v.ToString(),
            //    Value = ((int)v).ToString(),
            //}).ToList();

            //ViewBag.Role = HttpContext.Session.GetString("Role");+
            var data = _context.InvoiceMaster.Where(x => !x.Isdeleted).ToList();
            return View(data);
        }
        [HttpGet]
        //public IActionResult BindDropDown()
        //{
        //    //var devicemakelist = _context.ProjectMaster
        //    //                    .Where(w => w.isactive == true)
        //    //                   .Select(s => new SelectListItem()
        //    //                   {
        //    //                       Text = s.ProjectName,
        //    //                       Value = s.Id.ToString()
        //    //                   }).ToList();
        //    //return Json(devicemakelist);
        //}
        [HttpGet]
        public IActionResult Bindamount(int ProjectId)
        {
            var projectAmount = _context.ProjectMaster
                                .Where(w => w.Id == ProjectId)
                               .Select(s => s.projectamount).FirstOrDefault();
            return Json(projectAmount);
        }

        //post submitted todo data. if todo.TodoId is null then create new, otherwise edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SubmitForm([Bind("Id", "ProjectId", "Amount", "Duedate", "InvoiceNumber", "PendingAmount", "Isactive")] InvoiceMaster invoiceMasters)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    TempData[StaticString.StatusMessage] = "Error: Model state not valid.";
                    return RedirectToAction(nameof(Form), new { id = invoiceMasters.Id > 0 ? invoiceMasters.Id : 0 });
                }

                var user = _userManager.GetUserAsync(User).Result;

                //create new
                if (invoiceMasters.Id == 0)
                {
                    InvoiceMaster newinvoiceMaster = new InvoiceMaster();
                    newinvoiceMaster.ProjectId = invoiceMasters.ProjectId;
                    newinvoiceMaster.CreatedDate = DateTime.Now;
                    newinvoiceMaster.Amount = invoiceMasters.Amount;
                    newinvoiceMaster.Duedate = DateTime.Now;
                    newinvoiceMaster.InvoiceNumber = invoiceMasters.InvoiceNumber;
                    newinvoiceMaster.PendingAmount = invoiceMasters.PendingAmount;
                    newinvoiceMaster.Isverify = true;
                    newinvoiceMaster.CreatedBy = user.Id;
                    _context.InvoiceMaster.Add(newinvoiceMaster);
                    _context.SaveChanges();

                    TempData[StaticString.StatusMessage] = "Create new Invoice master item success.";
                    return RedirectToAction(nameof(Form), new { id = invoiceMasters.Id > 0 ? invoiceMasters.Id : 0 });
                }

                //edit existing
                InvoiceMaster editInvoicemaster = new InvoiceMaster();
                editInvoicemaster = _context.InvoiceMaster.Where(x => x.Id.Equals(invoiceMasters.Id)).FirstOrDefault();
                editInvoicemaster.ProjectId = invoiceMasters.ProjectId;
                editInvoicemaster.Amount = invoiceMasters.Amount;
                editInvoicemaster.InvoiceNumber = invoiceMasters.InvoiceNumber;
                editInvoicemaster.PendingAmount = invoiceMasters.PendingAmount;
                editInvoicemaster.Duedate = DateTime.Now;
                editInvoicemaster.UpdatedBy = user.Id;
                editInvoicemaster.UpdatedDate = DateTime.Now;
                editInvoicemaster.Isverify = true;
                _context.Update(editInvoicemaster);
                _context.SaveChanges();

                TempData[StaticString.StatusMessage] = "Edit existing invoice Masters item success.";
                return RedirectToAction(nameof(Form), new { id = invoiceMasters.Id > 0 ? invoiceMasters.Id : 0 });
            }
            catch (Exception ex)
            {

                TempData[StaticString.StatusMessage] = "Error: " + ex.Message;
                return RedirectToAction(nameof(Form), new { id = invoiceMasters.Id > 0 ? invoiceMasters.Id : 0 });
            }
        }

        //display invoiceMasters create edit form
        [HttpGet]
        public IActionResult Form(int id)
        {
            ViewBag.ProjectMasterSelectionList = _context.ProjectMaster
                               .Where(w => w.isactive == true)
                              .Select(s => new SelectListItem()
                              {
                                  Text = s.ProjectName,
                                  Value = s.Id.ToString()
                              }).ToList();
            //ViewBag.SelectionList = Enum.GetValues(typeof(DataSelection)).Cast<DataSelection>().Select(v => new SelectListItem
            //{
            //    Text = v.ToString(),
            //    Value = ((int)v).ToString(),
            //}).ToList();

            //create new
            if (id == 0)
            {
                InvoiceMaster newinvoicemaster = new InvoiceMaster();
                return View(newinvoicemaster);
            }

            //edit invoice master
            InvoiceMaster editnewinvoicemaster = new InvoiceMaster();
            editnewinvoicemaster = _context.InvoiceMaster.Where(x => x.Id.Equals(id)).FirstOrDefault();

            if (editnewinvoicemaster == null)
            {
                return NotFound();
            }

            return View(editnewinvoicemaster);

        }

        //display invoice master item for deletion
        [HttpGet]
        public IActionResult Delete(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var invoicemaster = _context.InvoiceMaster.Where(x => x.Id.Equals(id)).FirstOrDefault();
            return View(invoicemaster);
        }

        //delete submitted Invoice master item if found, otherwise 404
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SubmitDelete([Bind("Id")] InvoiceMaster Invoice)
        {
            try
            {
                var deleteInvoicemaster = _context.InvoiceMaster.Where(x => x.Id.Equals(Invoice.Id)).FirstOrDefault();
                if (deleteInvoicemaster == null)
                {
                    return NotFound();
                }

                deleteInvoicemaster.Isdeleted = true;
                deleteInvoicemaster.Isverify = false;
                _context.InvoiceMaster.Update(deleteInvoicemaster);
                _context.SaveChanges();

                TempData[StaticString.StatusMessage] = "Delete Invoice master item success.";
                return RedirectToAction(nameof(InvoiceIndex));
            }
            catch (Exception ex)
            {

                TempData[StaticString.StatusMessage] = "Error: " + ex.Message;
                return RedirectToAction(nameof(Delete), new { id = Invoice.Id > 0 ? Invoice.Id : 0 });
            }
        }

        //[HttpPost]
        //public async Task<IActionResult> AddOrEdit(DataMaster model)
        //{
        //    bool IsDataExist = false;

        //    DataMaster data = await _context.Datamaster.FindAsync(model.Id);

        //    if (data != null)
        //    {
        //        IsDataExist = true;
        //    }
        //    else
        //    {
        //        data = new DataMaster();
        //    }
        //    var user = _userManager.GetUserAsync(User).Result;
        //    //if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            data.Type = model.Type;
        //            data.Text = model.Text;
        //            data.Description = model.Description;
        //            data.Isactive = model.Isactive;

        //            if (IsDataExist)
        //            {
        //                data.UpdatedBy = user.Id;
        //                data.UpdatedDate = DateTime.Now;
        //                _context.Update(data);
        //            }
        //            else
        //            {
        //                data.CreatedBy = user.Id;
        //                data.CreatedDate = DateTime.Now;
        //                _context.Add(data);
        //            }

coderush/Views/InvoiceMaster/Delete.cshtml
@model InvoiceMaster
@{ ViewData["Title"] = "Delete Invoice"; }

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            @ViewData["Title"]
        </h1>
        <p>
            @await Html.PartialAsync(PartialView.StatusMessage, TempData[StaticString.StatusMessage])
        </p>

    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <form asp-controller="InvoiceMaster" asp-action="SubmitDelete" method="post">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Delete Invoice item? this process is irreversible</h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                                title="Collapse">
                            <i class="fa fa-minus"></i>
                        </button>
                        <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                            <i class="fa fa-times"></i>
                        </button>
                    </div>
                </div>
                <div class="box-body">
                    <input type="hidden" asp-for="Id" />
                    <div class="form-group">
                        <label asp-for="Id"></label>
                        <input asp-for="Id" class="form-control" disabled />
                    </div>
                    <div class="form-group">
                        <label>Is verify</label>
                        <input asp-for="Isverify" type="checkbox" class="flat-red" disabled />
                    </div>

                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <a href="/InvoiceMaster/InvoiceIndex" class="btn btn-default">Back</a>
                    <button type="submit" class="btn btn-danger">Delete</button>
                </div>
                <!-- /.box-footer-->
            </div>
        </form>

        <!-- /.box -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->



@section Styles{

}


@section Scripts{

    <partial name="_ValidationScriptsPartial" />
}

coderush/Views/InvoiceMaster/Form.cshtml
@model InvoiceMaster
@{ ViewData["Title"] = "Invoice Form"; }

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            @ViewData["Title"]
        </h1>
        <p>
            @await Html.PartialAsync(PartialView.StatusMessage, TempData[StaticString.StatusMessage])
        </p>

    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <form asp-controller="InvoiceMaster" asp-action="SubmitForm" method="post">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Create or edit existing Invoice item</h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                                title="Collapse">
                            <i class="fa fa-minus"></i>
                        </button>
                        <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                            <i class="fa fa-times"></i>
                        </button>
                    </div>
                </div>
             
                <div class="box-body">
                    <input type="hidden" asp-for="Id" />
                    <div class="form-group">
                        <label asp-for="ProjectId"></label>
                        <select name="ProjectId" class="form-control" id="invprojid" asp-items="@ViewBag.ProjectMasterSelectionList" asp-for="ProjectId"></select>
                        @*<input asp-for="ProjectId" id="invprojid" class="form-control" />*@
                        <span asp-validation-for="ProjectId" class="text-danger"></span>
                        @*<span class="text-danger hidespan spantext">Please enter Text</span>*@
                    </div>
                    <input type="hidden" id="invamountold" value="" />
                    <input type="hidden" id="invallamount" value="" />
                    <input type="hidden" id="projectid" value="" />
                    <div class="form-group">
                        <label asp-for="Amount"></label>
                        <input asp-for="Amount" id="invamount" class="form-control" />
                        <span asp-validation-for="Amount" class="text-danger"></span>
                        @*<span class="text-danger hidespan spantext">Please enter Text</span>*@
                    </div>
                    <div class="form-group">
                        <label asp-for="Duedate"></label>
                        <input type="date" asp-for="Duedate" class="form-control" />
                        <span asp-validation-for="Duedate" class="text-danger"></span>
                        @*<span class="text-danger hidespan spantext">Please enter Text</span>*@
                    </div>
                    <div class="form-group">
                        <label asp-for="InvoiceNumber"></label>
                        <input asp-for="InvoiceNumber" class="form-control" />
                        <span asp-validation-for="InvoiceNumber" class="text-danger"></span>
                        @*<span class="text-danger hidespan spantext">Please enter Text</span>*@
                    </div>
                    <div class="form-group">
                        <label asp-for="PendingAmount"></label>
                        <input asp-for="PendingAmount" id="invpendingamount" class="form-control" />
                        <span asp-validation-for="PendingAmount" class="text-danger"></span>
                        @*<span class="text-danger hidespan spantext">Please enter Text</span>*@
                    </div>
                    <div class="form-group">
                        <label asp-for="Isverify"></label>
                        <input asp-for="Isverify" type="checkbox" id="ckisactive" class="flat-red" />
                    </div>

                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <a href="/InvoiceMaster/InvoiceIndex" class="btn btn-default">Back</a>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
                <!-- /.box-footer-->
            </div>
        </form>

        <!-- /.box -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->


@section Styles{
    <!-- DataTables -->
    <link rel="stylesheet" href="~/adminlte/components/datatables.net-bs/css/dataTables.bootstrap.min.css">

}


@section Scripts{

    <partial name="_ValidationScriptsPartial" />

<script type="text/javascript">

 

    $("#invprojid").on('change', function () {
        var id = $(this).val();
        Bindamount(id);
    })

    var Bindamount = function (Id) {
        $.ajax({
            type: "GET",
            url: "/InvoiceMaster/Bindamount?ProjectId=" + Id,
            dataType: "json",
            data: {},
            contentType: "application/json",
            success: function (res) {
                //$("#txtdeviceworkphone").empty();
                $("#invamount").empty();
                $("#invamount").val(res);
                $("#invamountold").val(res);
            },
            error: function (res, err) {

            }
        });

    };

    $("#invamount").on('change', function () {

        var amt = $("#invamount").val();
        var amtold = $("#invamountold").val();
        if (amt < amtold) {
            var different = amtold - amt
            $("#invpendingamount").val(different);
        }
        if (amtold < amt) {
            $("#invpendingamount").val("");
        }
    })

    $("#invpendingamount").on("blur", function () {

        var amunt = $(this).val();
        var filter = /^\d*(?:\.\d{1,2})?$/;
        if (filter.test(amunt)) {
            $(".prjcurncyvalid").show();
            return false;
        }
        else {
            $(".prjcurncyvalid").hide();
            return false;
        }
    });
</script>

    @*<script type="text/javascript">

            $('#btnsave').click(function () {
                var id = $("#hideid").val();
                var type = $("#ddlSelectionList option:selected").val();
                var text = $("#datatext").val();
                var description = $("#datadescription").val();
                var isactive = $("#ckisactive").is(":checked");

                var Isvalid = true;
                if (text == null || text == undefined || text == "") {
                    $("#datatext").attr('maxlength', '50');
                    $(".spantext").show();
                    Isvalid = false;
                }

                if (description == null || description == undefined || description == "") {
                    $(".spandescription").show();
                    Isvalid = false;
                }

                if (type == null || type == undefined || type == "") {
                    $(".spanSelection").show();
                    Isvalid = false;

                }
                if (!Isvalid) {
                    return false;
                }
                $(".text-danger").hide();


                var fileData = new FormData();
                fileData.append('Id', id);
                fileData.append('Type', type);
                fileData.append('Text', text);
                fileData.append('Description', description);
                fileData.append('isactive', isactive);


                $.ajax({
                    url: '/DataMaster/SubmitForm',
                    type: "POST",
                    contentType: false,
                    processData: false,
                    data: fileData,
                    success: function (result) {
                        $("#AddData").modal('hide');
                        alert(result.message);
                        window.location.reload();
                    },
                    error: function (err) {
                        alert("Fail!");
                    }
                });
            });


        </script>*@

}

coderush/Views/InvoiceMaster/InvoiceIndex.cshtml
@model List<InvoiceMaster>
@{ ViewData["Title"] = "Invoice"; }


<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            @ViewData["Title"]
        </h1>
        <p>
            @await Html.PartialAsync(PartialView.StatusMessage, TempData[StaticString.StatusMessage])
        </p>

    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">List of Invoice item</h3>
                <div class="box-tools pull-right">
                    <a href="/InvoiceMaster/Form" class="btn btn-primary"><i class="fa fa-plus"></i></a>
                </div>
            </div>
            <div class="box-body">
                <div class="table-responsive">
                    <table id="grid" class="table table-striped" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>Sr No.</th>
                                <th width="20%">ProjectId</th>
                                <th width="10%">Amount</th>
                                <th width="10%">Duedate</th>
                                <th width="10%">InvoiceNumber</th>
                                <th width="10%">PendingAmount</th>
                                <th width="10%">Is verify</th>
                                <th width="5%">Edit</th>
                                <th width="5%">Delete</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                            <tr>
                                <td>
                                    @item.Id
                                </td>

                                <td>
                                    @item.ProjectId
                                </td>
                                <td>
                                    @item.Amount
                                </td>
                                <td>
                                    @item.Duedate
                                </td>
                                <td>
                                    @item.InvoiceNumber
                                </td>
                                <td>
                                    @item.PendingAmount
                                </td>
                                @*<td><span style="text-decoration-line:@(item.Isverify ? "line-through" : "none")">@item.Isverify</span></td>*@
                                <td>
                                    <input type="checkbox" class="flat-red" @(item.Isverify ? "checked" : "") onclick="return false;">
                                </td>
                                <td>
                                    <a href="/InvoiceMaster/Form/@item.Id"><i class="fa fa-edit"></i></a>
                                </td>
                                <td>
                                    <a href="/InvoiceMaster/Delete/@item.Id"><i class="fa fa-trash"></i></a>
                                </td>
                            </tr>
}
                        </tbody>
                    </table>
                </div>

            </div>
            <!-- /.box-body -->
        </div>

        <!-- /.box -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->



@section Styles{
    <!-- DataTables -->
    <link rel="stylesheet" href="~/adminlte/components/datatables.net-bs/css/dataTables.bootstrap.min.css">
}


@section Scripts{


    <!-- DataTables -->
    <script src="~/adminlte/components/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="~/adminlte/components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/jquery-ui.js"></script>
    <script src="~/js/Invoice.js"></script>

    <!-- page script -->
    <script type="text/javascript">
        $(document).ready(function () {

            $('#grid').DataTable({
                lengthChange: false,
                info: false,
                searching: true,
                dom: 'lrtip',
                scrollX: false,
                pageLength: 25,
            });

            //var Project = "#invprojid";
            //$(Project).empty();
            //$(Project).append($("<option></option>").val("").html("--Select--"));
            //$.each(res, function (index, object) {

            //    $(Project).append($("<option></option>").val(object.value).html(object.text));
            //});

            //$.each(selectValues, function (key, value) {
            //    $('#mySelect')
            //        .append($("<option></option>")
            //            .attr("value", key)
            //            .text(value));
            //});

        });
    </script>

}